# Generated by Django 5.1.3 on 2025-08-04 16:35

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, max_length=200, null=True)),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('registro_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeria/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de publicacion')),
                ('fin_publicacion', models.DateField(blank=True, default=None, null=True, verbose_name='Fin de publicacion')),
                ('publicacion_activa', models.BooleanField(default=False)),
                ('enviar_boletin', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=200)),
                ('copete', models.CharField(blank=True, max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('ajustar_imagen', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('epigrafe', models.TextField(blank=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo_destacado', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido_destacado', models.TextField(blank=True, null=True)),
                ('estilo_destacado', models.CharField(choices=[('bg-req-secondary', 'amarillo'), ('bg-req-primary text-white', 'azul'), ('bg-req-quaternary text-white', 'petroleo'), ('bg-req-quinary', 'rosa'), ('', 'sin color'), ('bg-req-tertiary text-white', 'verde')], default='', max_length=30, null=True)),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('registro_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('subtitulo', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('link_texto', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de publicacion')),
                ('fin_publicacion', models.DateField(blank=True, default=None, null=True, verbose_name='Fin de publicacion')),
                ('publicacion_activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico no válido')])),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.BooleanField(default=False)),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('registro_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
