# Generated by Django 5.1.3 on 2025-09-02 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_agente', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico no válido')])),
                ('estado', models.BooleanField(default=False)),
                ('email_validado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('registro_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Correo electrónico no válido')])),
                ('tipo_usuario', models.CharField(max_length=100)),
                ('tipo_sugerencia', models.CharField(max_length=100)),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
