# Generated by Django 5.1.3 on 2025-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_slider_titulo_color_alter_noticia_estilo_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='titulo_color',
            field=models.CharField(blank=True, choices=[('bg-req-primary text-white', '* texto blanco fondo azul'), ('bg-req-secondary', 'fondo-amarillo'), ('bg-req-quaternary text-white', 'fondo-petroleo'), ('bg-req-quinary', 'fondo-rosa'), ('bg-req-tertiary text-white', 'fondo-verde'), ('', 'sin color'), ('text-secondary', 'texto - amarillo'), ('text-quaternary text-white', 'texto - petroleo'), ('text-quinary', 'texto - rosa'), ('text-tertiary text-white', 'texto - verde'), ('text-primary text-white', 'texto blanco texto - azul')], default='', max_length=30, null=True),
        ),
    ]
