# Generated by Django 5.1.3 on 2025-09-03 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_slider_titulo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='sugerencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='apellido_nombre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico no válido')]),
        ),
    ]
