# Generated by Django 5.1.3 on 2025-09-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_sugerencia_apellido_remove_sugerencia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='mensaje',
            field=models.TextField(default=''),
        ),
    ]
