# Generated by Django 5.1.3 on 2025-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sugerencia_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='estilo_destacado',
            field=models.CharField(choices=[('bg-req-primary text-white', '* texto blanco fondo azul'), ('bg-req-secondary', 'fondo-amarillo'), ('bg-req-quaternary text-white', 'fondo-petroleo'), ('bg-req-quinary', 'fondo-rosa'), ('bg-req-tertiary text-white', 'fondo-verde'), ('', 'sin color'), ('text-warning', 'texto - amarillo'), ('txt-secondary', 'texto - blanco'), ('text-dark', 'texto - negro'), ('txt-quaternary', 'texto - petroleo'), ('text-danger', 'texto - rojo'), ('txt-quinary', 'texto - rosa'), ('txt-tertiary', 'texto - verde'), ('txt-primary', 'texto blanco texto - azul')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titulo_color',
            field=models.CharField(blank=True, choices=[('bg-req-primary text-white', '* texto blanco fondo azul'), ('bg-req-secondary', 'fondo-amarillo'), ('bg-req-quaternary text-white', 'fondo-petroleo'), ('bg-req-quinary', 'fondo-rosa'), ('bg-req-tertiary text-white', 'fondo-verde'), ('', 'sin color'), ('text-warning', 'texto - amarillo'), ('txt-secondary', 'texto - blanco'), ('text-dark', 'texto - negro'), ('txt-quaternary', 'texto - petroleo'), ('text-danger', 'texto - rojo'), ('txt-quinary', 'texto - rosa'), ('txt-tertiary', 'texto - verde'), ('txt-primary', 'texto blanco texto - azul')], default='', max_length=30, null=True),
        ),
    ]
