# Generated by Django 5.1.3 on 2025-03-05 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_agente', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico no válido')])),
                ('estado', models.BooleanField(default=False)),
                ('email_validado', models.BooleanField(default=False)),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('registro_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
