# Generated by Django 5.1.3 on 2025-03-05 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalhospital',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
