# Generated by Django 5.1.3 on 2025-03-06 11:09

import django.db.models.deletion
import django.utils.timezone
import uuid
import web.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_personalhospital_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de publicacion')),
                ('fin_publicacion', models.DateField(blank=True, default=None, null=True, verbose_name='Fin de publicacion')),
                ('publicacion_activa', models.BooleanField(default=False)),
                ('enviar_boletin', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Articulos/', validators=[web.helpers.validar_extension_archivo])),
                ('registro_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('registro_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='FileArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='institucional.articulo')),
            ],
        ),
    ]
