# Generated by Django 5.1.3 on 2025-03-07 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_articulo_filearticulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='enviar_boletin',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fin_publicacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='publicacion_activa',
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
