# Generated by Django 5.1.3 on 2025-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_alter_articulo_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo_documento',
            field=models.CharField(choices=[('protocolo', 'Protocolo'), ('sin Calificar', 'Sin Calificar'), ('manuel de procedimientos', 'manual de procedimientos')], default='', max_length=30, null=True),
        ),
    ]
