# Generated by Django 5.1.3 on 2025-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0008_remove_articulo_archivo_articulo_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo_documento',
            field=models.CharField(choices=[('sin Calificar', 'Sin Calificar'), ('protocolo', 'Protocolo'), ('manuel de procedimientos', 'Manual de procedimientos')], default='', max_length=30, null=True),
        ),
    ]
