# Generated by Django 5.1.3 on 2025-08-27 14:06

import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0009_alter_articulo_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='filearticulo',
            name='archivo_publico',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='filearticulo',
            name='archivo',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='documento'),
        ),
    ]
