# Generated by Django 5.1.3 on 2025-08-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0010_filearticulo_archivo_publico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filearticulo',
            old_name='archivo',
            new_name='archivo_restringido',
        ),
    ]
