# Generated by Django 5.1.3 on 2025-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0012_alter_filearticulo_archivo_restringido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalhospital',
            name='numero_agente',
            field=models.BigIntegerField(default=0),
        ),
    ]
