# Generated by Django 5.1.3 on 2025-09-30 12:40

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0014_alter_filearticulo_archivo_restringido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearticulo',
            name='archivo_restringido',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='documento'),
        ),
    ]
